import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../../app/store'
import { registerAsync } from './registerUserApi';

interface RegisterProps {
  name: string;
  email: string;
  password: string;
}

export enum Status {
  Idle = "idle",
  Loading = "loading",
  Failed = "failed"
}

export interface RegisterState {
  value: RegisterProps | null;
  status: Status;
}

const initialState: RegisterState = {
  value: null,
  status: Status.Idle,
};

export const registerSlice = createSlice({
  name: 'registerSlice',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setRegister: (state, action: PayloadAction<RegisterProps>) => {
      state.value = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(registerAsync.pending, (state) => {
        state.status = Status.Loading;
      })
      .addCase(registerAsync.fulfilled, (state, action) => {
        state.status = Status.Idle;
        state.value = action.payload;
        console.log(action.payload, "1");
        console.log(state.value, "2");

      })
      .addCase(registerAsync.rejected, (state) => {
        state.status = Status.Failed;
      });
  },
});

export const { setRegister } = registerSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectRegister = (state: RootState) => state.register.value;
export const selectStatusRegister = (state: RootState) => state.register.status;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.


export default registerSlice.reducer;
